name: blog-deply
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: chins-learn/vuepress-theme-reco-blog@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: chins-learn/chins-learn.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: public/
        